gRPC require java.instrument module
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linecorp.armeria.spring.GrpcServiceRegistrationBean]: Factory method 'pingService' threw exception; nested exception is java.lang.NoClassDefFoundError: java/lang/instrument/ClassFileTransformer
...
Caused by: java.lang.ClassNotFoundException: java.lang.instrument.ClassFileTransformer
 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[na:na]
 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[app.jar:na]
 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]